#!/bin/sh

module-rebuild populate
oldversion=`ls -l /usr/src/linux | grep -o linux-.*` 
#emerge -u gentoo-sources
eselect kernel list
echo "Select number"
read num
eselect kernel set $num
cd /usr/src/linux
cp ../"$oldversion"/.config .
#make oldconfig
make menuconfig
make && make modules_install
version=`ls -l /usr/src/linux | grep -o [0-9].[0-9].[0-9].* | sed 's/-gentoo//g'` 
cp -i arch/i386/boot/bzImage /boot/gentoo-"$version"
module-rebuild rebuild
vi /etc/lilo.conf
/sbin/lilo

echo "emerge -P gentoo-sources and rm /lib/modules/$oldversion"
